version: '3'
services:
  mysql:
    restart: always
    image: mysql:8.4
    container_name: mysql8-test
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      #- ./mysql/data:/var/lib/mysql
      #- ./mysql/logs:/var/log
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      TZ: Asia/Shanghai
    ports:
      - 3306:3306
    #客户端管理工具：https://www.mysql.com/products/workbench/

  redis:
    restart: always
    image: redis:latest
    container_name: redis7-test
    #privileged: true # 获取宿主机root权限
    volumes:
      - ./redis/conf:/etc/redis
      #- ./redis/data:/data
      #- ./redis/logs:/var/local/redis
    command: ["redis-server","/etc/redis/redis.conf"] # 指定配置文件启动redis-server进程
    ports:
      - 6379:6379
    #客户端管理工具：https://github.com/qishibo/AnotherRedisDesktopManager

  rabbitmq:
    restart: always
    image: rabbitmq:management
    container_name: rabbitmq-test
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456
    #volumes:
      #- ./rabbitmq/conf:/etc/rabbitmq
      #- ./rabbitmq/data:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  
  mongodb:
    restart: always
    image: mongo:latest
    container_name: mongo-test
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_DATABASE: testdb
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    #volumes:
      #- ./mongo/conf:/data/configdb
      #- ./mongo/data:/var/lib/mongodb
      #- ./mongo/logs:/var/log/mongodb/mongod.log
    #command: mongod --config /etc/mongo/mongod.conf
    ports:
      - "27017:27017"
    #客户端管理工具：https://www.mongodb.com/try/download/compass

  kanboard:
    image: kanboard/kanboard:latest
    ports:
      - "8010:80"
      - "443:443"
    volumes:
      - ./kanboard/data:/var/www/app/data
      - ./kanboard/plugins:/var/www/app/plugins
      - ./kanboard/ssl:/etc/nginx/ssl